import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import TestSingleData from "@/TestSingleData";
import TestMultipleData from "@/TestMultipleData";
import CreateUserMutation from "@/CreateUserMutation";
import Header from "./Components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div>
        <h1 style={{ color: "orange" }}>Fetch Single Record</h1>
        <TestSingleData />
        <br />
        <br />

        <h1 style={{ color: "blue" }}>Fetch Mutltiple Record</h1>
        <TestMultipleData />

        <h1 style={{ color: "green" }}>Create User Mutations</h1>
        <CreateUserMutation />
      </div> */}
      <Header />
    </>
  );
}
